name: 'Publish Workspace'
description: 'Publish the workspace that was version bumped in the specified commit'
inputs:
  sha:
    description: 'Version bump commit SHA. The commit must contain one package.json change'
runs:
  using: 'node16'
  main: 'index.js'
