name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14.0]
    name: Node ${{ matrix.node-version }} build
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pre-Install
        run: npm install -D --arch=x64 --platform=linux turbo

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Pre-Build
        run: npm run pre-build

      - name: Build
        run: npm run build
