name: Compliance
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  compliance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14.0]
    name: Compliance check
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enforce Title
        uses: ./.github/actions/enforce-title
        with:
          pull-request-title: ${{ github.event.pull_request.title }}
