name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CDN_ASSET_HOST: https://xxx.cdn.introhive.com/
  AWS_ROLE_ARN: rolexxxxxx
  AWS_BUCKET_NAME: ih-bucket-name

jobs:
  publish:
    if: ${{ github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'bump') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14.0]

    name: Node ${{ matrix.node-version }} publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pre-Install
        run: npm install -D --arch=x64 --platform=linux turbo

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Pre-Build
        run: npm run pre-build

      - name: Build
        run: npm run build

      - name: Get Workspace Info
        id: workspace
        uses: ./.github/actions/workspace-info
        with:
          sha: ${{ github.sha }}

      - name: Pre-Publish
        run: npm run pre-publish -w ./packages/${{ steps.workspace.outputs.workspace-name }} --if-present

      - name: Tag
        uses: ./.github/actions/tag
        with:
          tag: ${{ steps.workspace.outputs.workspace-tag }}
          sha: ${{ github.sha }}
          user: "bumpbot"
          email: "bumpbot@users.noreply.github.com"
          message: "Tag created by publish workflow"
