name: Title Check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  title-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14.0]
    name: Title check
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Title check
      uses: ./.github/actions/title-check
      with:
        pull-request-title: ${{ github.event.pull_request.title }}
